config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :books, only: [:new, :create, :show] do
    resources :pages, only: [:show] do
      member do
        get 'search'
      end
    end
    resources :bookmarks, only: [:create, :update]
  end
  resources :highlights, only: [:index]
  get 'highlights/create', to: 'highlights#create'
  get 'highlights/load', to: 'highlights#load'
  get 'highlights/delete', to: 'highlights#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_one :bookmark
  has_many :highlights
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :content
  end
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :book
  belongs_to :user

  with_options presence: true do
    validates :pagenum
  end
end

app/models/highlight.rb
class Highlight < ApplicationRecord
  belongs_to :book
  belongs_to :user

  with_options presence: true do
    validates :text
    validates :pagenum
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books
  has_many :highlights
  has_many :bookmarks

  with_options presence: true do
    validates :name
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
  #   end
  # end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.save
    redirect_to root_path
  end

  def update
    @book = Book.find(params[:book_id])
    @bookmark = @book.bookmark
    @bookmark.update(bookmark_update_params)
    redirect_to root_path
  end

  private

  def bookmark_params
    params.require(:page).permit(:pagenum, :book_id).merge(user_id: current_user.id)
  end

  def bookmark_update_params
    params.permit(:pagenum, :book_id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]
  before_action :move_to_index, only: [:show]

  def index
    if user_signed_in?
      @books = current_user.books
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    if Bookmark.exists?(book_id: @book.id)
      @pagenum = @book.bookmark.pagenum
      summary = exec(@book.content[1000 * (@pagenum - 1), 300])
      if summary != nil
        @summary = summary[0].gsub("\r\n", "")
      else
        @summary = "該当の要約はありません。"
      end
      if @pagenum != 1
        before_summary = exec(@book.content[1000 * (@pagenum - 2), 300])
        if before_summary != nil
          @before_summary = before_summary[0].gsub("\r\n", "")
        else
          @before_summary = "該当の要約はありません。"
        end
      end
      @keywords = keyword(@book.content[1000 * (@pagenum - 1), 300])
    end
  end

  private

  def move_to_index
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to root_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :content, :image).merge(user_id: current_user.id)
  end
  
  def exec(sentence) 
    url = URI.parse("https://api.a3rt.recruit-tech.co.jp/text_summarization/v1")
    separation = "。"
    line_count = get_line_count(sentence, separation)
    
    # 文章数が1つの場合APIがエラーを出す
    if line_count <= 1
      return [sentence]
    end

    post_data = { 
      'apikey' => ENV["A3RT_API_KEY"],
      'sentences' => sentence,
      'linenumber' => 1,
      'separation' => separation
    }

    res = post_request(url, post_data, true);
    return nil if res.code != "200"

    result = JSON.parse(res.body)
    return result['summary']
  end

  def get_line_count(sentence, separation)
    sentence.count(separation)
  end

  def post_request(url, data, use_ssl = true) 
    req = Net::HTTP::Post.new(url.request_uri)
    req.set_form_data(data)
    
    Net::HTTP.start(url.host, url.port, 
      :use_ssl => use_ssl, 
      :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|
        http.request(req)
      end
  end

  def keyword(document)
    require 'cotoha'
    client_id = ENV["COTOHA_API_ID"]
    client_secret = ENV["COTOHA_API_SECRET_KET"]
    client = Cotoha::Client.new(client_id: client_id, client_secret: client_secret)
    client.create_access_token
    client.keywords(document: document)
  end
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :move_to_index, except: [:index, :load]
  
  def index
    @highlights = current_user.highlights
  end

  def load
    items = Highlight.pluck(:text)
    render json: { post: items }
  end

  def delete
    highlight = Highlight.find_by(text: params[:text])
    highlight.destroy
  end

  def create
    highlight = Highlight.new(page_highlight_params)
    highlight.save
  end

  private

  def move_to_index
    unless params[:text]
      redirect_to root_path
    end
  end

  def page_highlight_params
    params.permit(:text, :book_id, :pagenum).merge(user_id: current_user.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index, only: [:show]

  def show
    @pagenum = params[:id].to_i
  end

  def search
    require 'google/apis/customsearch_v1'
    api_key = ENV["GOOGLE_CUSTOM_SEARCH_KEY"]
    cse_id = ENV["GOOGLE_CUSTOM_SEARCH_CSE_ID"]
    searcher = Google::Apis::CustomsearchV1::CustomSearchAPIService.new
    searcher.key = api_key
    query = params.permit(:search)
    results = searcher.list_cses(q: query, cx: cse_id)
    @items = results.items
    @query = query[:search]
  end

  private

  def move_to_index
    @book = Book.find(params[:book_id])
    if current_user.id != @book.user_id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/index.html.erb
<%= render "shared/header" %>
<div class="book-contents">
  <h2 class="title">あなたの本棚</h2>
    <ul class='book-lists'>
      <% if user_signed_in? %>
        <% @books.each do |book| %>
          <li class = "list">
            <div class="book-image-content">
              <%if book.image.attached? %>
                <%= image_tag book.image, class:"book-image"%>
              <% else %>
                <%= image_tag 'png.png', class:"book-image"%>
              <% end %>
            </div>
            <div class="book-title">
              <%= link_to book.title, book_path(book), class:"link-to" %>
            </div>
          </li>
        <% end %>
      <% else %>
        <div class="book-title">
          ログインまたは会員登録をしてください。
        </div>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <div class="highlight-bar">
        <%= link_to "あなたのハイライト", highlights_path(id: current_user.id), class:"link-to" %>
      </div>
      <div class="new-book-bar">
        <%= link_to "本追加", new_book_path, class:"link-to" %> 
      </div>
    <% end %>
</div>
<% breadcrumb :root %>

app/views/books/new.html.erb
<%= render "shared/header" %>

<div class="contents row">
  <div class="container-title">
    <h2>新しい本の追加</h2>
  </div>
  <div class="new-book-container">
    <%= form_with model: @book, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_field :title %><br>
      <%= f.text_area :content %><br>
      <%= f.file_field :image %><br>
      <%= f.submit "本を追加する" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<%= render "shared/header" %>
<div class='main-show'>
  <div class='book-list-show'>
    <div class='list-show'>
      <div class="book-image-content">
      <%if @book.image.attached? %>
        <%= image_tag @book.image, class:"book-image"%>
      <% else %>
        <%= image_tag 'png.png', class:"book-image"%>
      <% end %>
      </div>
      <div class="book-title">
        <%= @book.title %>
      </div>
    </div>
  </div>
  <div class='book-list-menu'>
    <div class='book-first-list'>
      <%= link_to '初めから読む', book_page_path(book_id: @book.id, id: 1), class:"link-to" %>
    </div>
    <% if Bookmark.exists?(book_id: @book.id) %>
    <div class='book-continued-list'> 
      <%= link_to '続きから読む', book_page_path(book_id: @book.id, id: @book.bookmark.pagenum), class:"link-to" %>
    </div>
    <% end %>
  </div>
  
  <div class='keyword'>
    <div class='keyword-message'>
      <% if @keywords != nil %>
        <%= image_tag('writing_icon') %>続きのキーワードはこちら<br>
        <% @keywords["result"].each_with_index do |keyword, i| %>
          <%= i+1 %>位.<%= keyword["form"] %><br>
        <% end %>
      <% end %>
    </div>
  <div class='summary'>
    <% if @summary != nil %>
    <div class='summary-message'>
      <%= image_tag('writing_icon') %>続きの要約はこちら<br>
      <%= @summary %>
    </div>
    <% end %>
    <% if @before_summary != nil %>
    <div class='summary-message'>
      <%= image_tag('writing_icon') %>以前の要約はこちら<br>
      <%= @before_summary %>
    </div>
    <% end %>
  </div>
</div>
<% breadcrumb :books %>

app/views/highlights/index.html.erb
<%= render "shared/header" %>
<div class="highlight-contents">
  <div class="highlight-index">
    あなたのハイライト一覧
  </div>
  <div class="highlight-content-list">
    <div class="highlight-text">
      ハイライト
    </div>
    <div class="highlight-title">
      本のタイトル
    </div>
    <div class="highlight-page">
      ページ
    </div>
  </div>
  <% @highlights.each do |highlight| %>
  <div class="highlight-content">
    <div class="highlight-text">
      「<%= highlight.text %>」
    </div>
        <div class="highlight-title">
      <%= highlight.book.title %>
    </div>
    <div class="highlight-page">
      <%= highlight.pagenum %>ページ
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSmart</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= breadcrumbs separator: " &rsaquo; " %>
  </body>
</html>

app/views/pages/search.html.erb
<%= render "shared/header" %>
<div class="search-results">
  <div class="search-message">
    <%= image_tag('writing_icon')%>検索結果はこちら<br>
    <span class="mgr-10">検索ワード：</span>~<%= @query %>~<br>
  </div>
  <div class="search-result">
    <% if @items != nil %>
      <% @items.each_with_index do |item, i| %>
        <span class="mgr-10"><%= i+1 %>.</span>
        <span class="mgr-10"><%= item.title %></span>
        <%= link_to 'このページへ移動する(外部ページ)', item.link, class:"webpage-link" %><br>
      <% end %>
    <% else %>
    <br>Webページは見つかりませんでした。<br>
    <% end %>
  </div>
  <%= link_to "元のページに戻る", book_page_path, class:"link-to" %>
</div>
<% breadcrumb :searches %>

app/views/pages/show.html.erb
<%= render "shared/header" %>
<div class='page-text'>
  <div class='page-text-contents'>
    <p class='page-text-content' id='page-text-content'>
    <% if @pagenum ==1 %>
      <%= @book.title %><br>
    <% end %>
      <%= @book.content[1000 * (@pagenum - 1), 1000] %><br>
    </p>
  </div>

  <h2 class='page-number'>
    <%= @pagenum %>
  </h2> 

  <div class='page-list-menu'>
    <% unless @book.content[1000 * (@pagenum - 1), 1000].length < 1000 %><br>
    <div class='next-page'>
      <%= link_to image_tag('next_icon.png', size:'28x28'), book_page_path(book_id: @book.id, id: (@pagenum + 1)) %>
    </div>
    <% end %>
    <% if @pagenum > 1 %>
    <div class='back-page'>
      <%= link_to image_tag('back_icon.png', size:'28x28'), book_page_path(book_id: @book.id, id: (@pagenum - 1)) %>
    </div>
    <% end %>
  </div>

  <div class='page-bookmark-menu'>
    <% unless Bookmark.exists?(book_id: @book.id) %>
    <div class='bookmark-image'>
      <%= image_tag 'bookmark', class: 'bookmark-icon'%>
    </div>
    <div class='bookmark-message'>
      <%= link_to '新しくしおりを挟む', book_bookmarks_path(page: {book_id: @book.id, pagenum: @pagenum}), method: :post, class:"link-to", id:"bookmark", href: "#modal01" %>
    </div>
    <% else %>
    <div class='bookmark-image'>
      <%= image_tag 'bookmark', class: 'bookmark-icon' %>
    </div>
    <div class='bookmark-message'>
      <%= link_to 'しおりを挟む', book_bookmark_path(params: {book_id: @book.id, pagenum: @pagenum}), method: :put, class:"link-to", id:"bookmark", href: "#modal01" %>
    </div>
    <% end %>
  </div>
</div>

<div class="modal" id="modal01">
  <div class="overLay"></div>
  <div class="inner">
    <% if Bookmark.exists?(book_id: @book.id) %>
      <% todaypages = @pagenum - @book.bookmark.pagenum %>
    <% else %>
      <% todaypages = @pagenum %>
    <% end %>
    
    P.<%= @pagenum %>にしおりを挟みました<br>
    <% if todaypages > 0 %>
      今日は<%= todaypages %>ページ読みました！<br>
    <% end %>
    <% if todaypages >= 10 %>
      たくさん読みましたね！さすがです&#x1f973; &#x1f973; &#x1f973;<br>
    <% else %>
      お疲れさま！！<br>
    <% end %>

    <% unless Bookmark.exists?(book_id: @book.id) %>
    <%= link_to 'あなたの本棚に戻る', book_bookmarks_path(page: {book_id: @book.id, pagenum: @pagenum}), method: :post %>
    <% else %>
    <%= link_to 'あなたの本棚に戻る', book_bookmark_path(params: {book_id: @book.id, pagenum: @pagenum}), method: :put %>
    <% end %>
  </div>
</div>
<% breadcrumb :pages %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class='page-header'>
  <div class= 'header-logo'>
    <%= link_to image_tag('book_icon.png'), root_path %>
    <%= link_to 'Book Smart', root_path, class:"header-title" %>
  </div>
  <div class='header-menu'>
    <ul class='user-lists'>
      <% if user_signed_in? %>
        <li><%= current_user.name %><li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "user-link-to" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "user-link-to" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "user-link-to" %></li>
      <% end %>
    </ul>
  </div>
</header>